name: VirusTotal

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !contains(github.ref, '-beat.') }}
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            .exe$
            .dmg$
